Add support for craftguide mod recipe registration.
minetest-mods/technic pull request #584
Opened 2021-03-26 18:15 UTC by sfence

So, technic crafting recipes should be visible in [Crafting Guide](https://content.minetest.net/packages/jp/craftguide/) like they are visible in unified_inventory.

2021-03-26 20:35 UTC, S-S-X commented
Have to add craftguide to .luacheckrc read_globals and fix this:
```
    technic/machines/register/recipes.lua:77:11: shadowing definition of variable index on line 52
```

2021-03-26 20:47 UTC, S-S-X requested changes
Requested small changes to clear linter tests, otherwise looks okay for me.

However I think it would be good to move both craftguide and unified_inventory stuff to separate file to keep technic specific registrations bit cleaner but IMO that can be done later too.
Maybe just add issue for that if not doing under this PR.

2021-03-26 20:47 UTC, S-S-X commented on technic/machines/register/recipes.lua
> +      end
Use `_` instead of `index` as index value is not actually used at all in for loop.
Underscore has special meaning for linter: clears unused variable warning.
Also clears warnings about shadowing previous definition.
Also spaces -> tabs as to keep indentation similar how it is in other parts.

2021-03-26 21:16 UTC, sfence commented on technic/machines/register/recipes.lua
> +      end
Thanks for the quick reaction.
I have updated .luacheckrc, replaced spaces with tabs and the index variable is by _.

2021-03-27 10:06 UTC, sfence commented
I have added support for i3 inventory mod delivered from craftguide mod too.

2021-03-28 17:29 UTC, SmallJoker commented on technic/machines/register/recipes.lua
> +		if (craftguide.register_craft or have_i3) then
/recipes.lua:75: attempt to index global 'craftguide' (a nil value)

2021-03-28 17:30 UTC, SmallJoker commented on technic/machines/register/recipes.lua
> +			end
`local items = table.concat(data.input, ", ")`

2021-03-28 17:31 UTC, SmallJoker commented on technic/machines/register/recipes.lua
> +			if craftguide.register_craft then
/recipes.lua:88: attempt to index global 'craftguide' (a nil value)

2021-03-28 17:33 UTC, SmallJoker commented on technic/machines/register/recipes.lua
> +	if have_i3 and i3.register_craft_type and data.output_size == 1 then
I don't think checking for `register_craft_type` is necessary here. All (reasonable new?) versions have this API function.

2nd suggestion: Move the `data.output_size == 1` check one level up, and include all craft guide registrations inside to avoid duplication.

2021-03-28 17:33 UTC, SmallJoker commented on technic/depends.txt
> +craftguide?
You might as well remove this file. technic now requires Minetest 5.0.0 anyway, hence this is superfluous.

2021-03-29 06:38 UTC, sfence commented on technic/depends.txt
> +craftguide?
The file has been removed by commit 7600b7e.

2021-03-29 06:41 UTC, sfence commented on technic/machines/register/recipes.lua
> +		if (craftguide.register_craft or have_i3) then
My fault. I forgot to test it without craft guide mod enabled.

Should be fixed now.

2021-03-29 18:48 UTC, SmallJoker commented on technic/machines/register/recipes.lua
> +		if (have_cg or have_i3) then
Duplicated `(have_cg or have_i3)` check.

2021-03-29 18:51 UTC, SmallJoker commented on technic/machines/register/recipes.lua
> +			local items = table.concat(data.input, ", ");
FYI: Lua does only require semicolons as long you're not doing multiple assignments per line (which you shouldn't do anyway).

This is not a change request.

2021-03-29 20:01 UTC, sfence commented on technic/machines/register/recipes.lua
> +		if (have_cg or have_i3) then
Fixed.

2021-03-29 20:22 UTC, SmallJoker commented
Thanks. Looks good. Will merge in a few days if there are no objections.

2021-04-14 14:20 UTC, merged